service:
    name: teamup-calendar-slack-bot

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

# Add the serverless-webpack plugin
plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs12.x
    apiGateway:
        minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        TEAMUP_TOKEN: ${file(./.env.yml):TEAMUP_TOKEN}
        CALENDAR_ID: ${file(./.env.yml):CALENDAR_ID}
        SLACK_WEBHOOK_URL: ${file(./.env.yml):SLACK_WEBHOOK_URL}

functions:
    send-events:
        handler: handler.sendEvents
        events:
            - http:
                  method: get
                  path: hello
            - schedule:
                  rate: cron(0 22 ? * MON-FRI *)
